// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectName.Infrastructure.Database;

namespace ProjectName.Infrastructure.Migrations
{
    [DbContext(typeof(ReportContext))]
    [Migration("20191122095728_InitialCreateReport")]
    partial class InitialCreateReport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectName.Infrastructure.Database.Report", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContractNo")
                        .HasMaxLength(20);

                    b.Property<string>("ContractType")
                        .HasMaxLength(255);

                    b.Property<string>("ContractTypeCode")
                        .HasMaxLength(20);

                    b.Property<int?>("ContractTypeId");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .HasMaxLength(512);

                    b.Property<int?>("EmployeeId");

                    b.Property<int?>("EmployeerId");

                    b.Property<string>("EmployeerName")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("ExpireDate");

                    b.Property<int?>("Index");

                    b.Property<string>("Note")
                        .HasMaxLength(512);

                    b.Property<float?>("Salary");

                    b.Property<string>("SignCode")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("SignDate");

                    b.Property<int?>("SignId");

                    b.Property<string>("SignName")
                        .HasMaxLength(255);

                    b.Property<string>("SignOrg")
                        .HasMaxLength(255);

                    b.Property<string>("SignPos")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("StartDate");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(20);

                    b.Property<string>("WorkingTime")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ProjectName.Infrastructure.Database.User", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
